# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [3]:
import numpy as np # Importing NumPy.

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5) 

In [4]:
print('Dimension (number of axes):', A.ndim) # dimension (number of axes)
print('Shape:', A.shape) # shape
print('Size:', A.size) # size
print('Datatype:', A.dtype) # datatype 

Dimension (number of axes): 2
Shape: (3, 5)
Size: 15
Datatype: int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [62]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [63]:
print('Elementwise subtraction:\n', B - C) # Elementwise subtraction
print('\n Elementwise multiplication:\n', B * C) # Elementwise multiplication.
print('\n Matrix multiplication:\n', B @ C) # Matrix multiplication (by default you should use the @ operator).
print('\n Matrix multiplication:\n', B.dot(C))

Elementwise subtraction:
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

 Elementwise multiplication:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

 Matrix multiplication:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]

 Matrix multiplication:
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
print(np.exp(B)) # Exponentiate each number elementwise (use the np.exp function).

print('\n Minimum value in the whole matrix:', np.min(B)) # Calculate the minimum value in the whole matrix.

print('\n Minimum value in each row:', B.min(axis=1)) # Calculcate the minimum value in each row.

print('\n Minimum value in each column:', B.min(axis=0)) # Calculcate the minimum value in each column.

print('\n Index value for the minimum value in the whole matrix:', np.argmin(B)) # Find the index value for the minimum value in the whole matrix (hint: use np.argmin).

print('\n Index value for the minimum value in each row:', np.argmin(B, axis=1)) # Find the index value for the minimum value in each row (hint: use np.argmin).

print('\n Sum for all elemnts:', np.sum(B)) # Calculate the sum for all elements.

print('\n Mean for each column:', np.mean(B, axis=1)) # Calculate the mean for each column.

print('\n Median for each column:', np.median(B, axis=1))  # Calculate the median for each column.

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

 Minimum value in the whole matrix: 1

 Minimum value in each row: [1 4 7]

 Minimum value in each column: [1 2 3]

 Index value for the minimum value in the whole matrix: 0

 Index value for the minimum value in each row: [0 0 0]

 Sum for all elemnts: 45

 Mean for each column: [2. 5. 8.]

 Median for each column: [2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [30]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [31]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
# It means that you are selecting or indexing data along a single dimension of the array. In my example, 
# using A[1] selects the entire second row of the array.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [32]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [33]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [35]:
for i in A.flatten(): # You can also use ravel().
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [76]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# The code first creates an array 'a' with values from 0 to 29. It then reshapes this array into the array 'b' with 
# three axes (dimensions). 'b' consists of 2 arrays, each with three rows and five columns.

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [37]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [38]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [19]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print('\n', b)
print('\n', A + b)

[[1 2]
 [3 4]]

 [2 2]

 [[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2. 
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [63]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [27]:
def add_mult_matrices(A, B, add_or_multiply):
    
    if not (isinstance(A, np.ndarray) and isinstance(B, np.ndarray)):
        raise Exception('Please provide two matrices.')
    
    if add_or_multiply == 'add':
        if not A.shape == B.shape:
            raise ValueError('Same shape required for matrix addition.')
        else: 
            return A + B
        
    elif add_or_multiply == 'multiply':
        if not A.shape[1] == B.shape[0]:
            raise ValueError('Columns and rows must be the shame length in matrix multiplication')
        else:
            return A @ B
        
    else:
        raise Exception('the add_or_multiply argument must be "add" or "multiply". ')

print(' B-2A=\n', add_mult_matrices(B, -2 * A, 'add'))

 B-2A=
 [[ 2  0]
 [ 1 -1]]


In [28]:
print('\n 3C-E:\n', add_mult_matrices(3 * C, -E, 'add'))

NameError: name 'E' is not defined

In [29]:
print('\n AC:\n', add_mult_matrices(A, C, 'multiply'))


 AC:
 [[ 8 10]
 [ 4  7]]


In [30]:
print('\n CD=\n', add_mult_matrices(C, D, 'multiply'))

ValueError: Columns and rows must be the shame length in matrix multiplication

In [31]:
print('\n CB=\n', add_mult_matrices(C, B, 'multiply'))


 CB=
 [[33 25]
 [ 6  6]]


**Chap2. Question 2**

In [32]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print(A)
print(B)
print(C)

[[1 2]
 [2 4]]
[[2 1]
 [1 3]]
[[4 3]
 [0 2]]


In [120]:
AB = A @ B
AC = A @ C

print(A @ B)
print('\n', A @ C)

if (AB == AC).all():
    print("\nAB = AC")
else:
    print("AB ≠ AC")

if (B == C).all():
    print("B = C.")
else:
    print("B ≠ C")

[[ 4  7]
 [ 8 14]]

 [[ 4  7]
 [ 8 14]]

AB = AC
B ≠ C


**Chap2. Question 3**

In [6]:
A = np.array ([[1, 1, 1], [1, 2, 3], [1, 3, 4]])
D = np.array ([[2, 0, 0], [0, 3, 0], [0, 0, 4]])

print("AD= \n", A @ D)
print("\nDA=\n", D @ A)

AD= 
 [[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

DA=
 [[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2**

In [20]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])

print('The matrix is equal to:\n', A @ B)

The matrix is equal to:
 [[-2  2]
 [ 2 -2]]


**Chap 6. Question 1**

In [24]:
A = np.array([[5, 6], [4, 5]])
B = np.array([[6, 4], [3, 3]])
A_inv = np.linalg.inv(A)
print(A_inv)

# Checking if A @ A_inv is the identity matrix (due to round-off error in the PC, we use np.allclose.)
print('\n', A @ A_inv)
print('\n', np.allclose(A @ A_inv, np.eye(2)))

B_inv = np.linalg.inv(B)
print('\n', B_inv)

# Check if M1 @ M1_inv is the identity matrix (due to round-off error in the PC, we use np.allclose.)
print('\n', B @ B_inv)
print('\n', np.allclose(B @ B_inv, np.eye(2)))

[[ 5. -6.]
 [-4.  5.]]

 [[ 1.00000000e+00  0.00000000e+00]
 [-3.55271368e-15  1.00000000e+00]]

 True

 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]

 [[1. 0.]
 [0. 1.]]

 True


**Quiz p.19, Question 3**

In [36]:
A = np.array([[2, 2], [1, 2]])
A_inv = np.linalg.inv(A)
print(A_inv)

print('\n', A @ A_inv)
print(np.allclose(A @ A_inv, np.eye(2)))

[[ 1.  -1. ]
 [-0.5  1. ]]

 [[1. 0.]
 [0. 1.]]
True


**Chap10. Question 1 a)**

In [13]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
b = np.array([-7, 5, 2])

# The solution to the system of equations.
x = np.linalg.solve(A, b)
print('\n', x)

# Double checking if Ax = b.
print('\n', A @ x)


 [ 3.  4. -6.]

 [-7.  5.  2.]


**Chap10. Question 1 b)**

In [14]:
A = np.array([[1, -2, 3], [-1, 3, -1], [2, -5, 5]])
b = np.array([1, -1, 1])

# The solution to the system of equations.
x = np.linalg.solve(A, b)
print(x)
# Double checking if Ax = b.
print('\n', A @ x)

[ 8.  2. -1.]

 [ 1. -1.  1.]


**Chap 12. Question 1**

In [37]:
A = np.array([[3, -7, -2], [-3, 5, 1], [6, -4, 0]])
A_inv = np.linalg.inv(A)
print(A_inv)

# Check if M1 @ M1_inv is the identity matrix (due to round-off error in the PC, we use np.allclose.)
# print(A @ A_inv)
print('\n', np.allclose(A @ A_inv, np.eye(3)))

[[ 0.66666667  1.33333333  0.5       ]
 [ 1.          2.          0.5       ]
 [-3.         -5.         -1.        ]]

 True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [125]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [126]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [127]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
